//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renting.MasterServices.Infraestructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarningMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarningMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renting.MasterServices.Infraestructure.Resources.WarningMessages", typeof(WarningMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El accesorio no existe en la base de datos.
        /// </summary>
        public static string Accessory_Not_Exist {
            get {
                return ResourceManager.GetString("Accessory_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La llave {0} no fue encontrada en la cache.
        /// </summary>
        public static string CacheKey_Not_Exist {
            get {
                return ResourceManager.GetString("CacheKey_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vehículo ya tiene un acta de entrega registrada.
        /// </summary>
        public static string Existing_Delivery_Certificate {
            get {
                return ResourceManager.GetString("Existing_Delivery_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen las condiciones de entrega.
        /// </summary>
        public static string Not_Exixting_Delivery_Condition {
            get {
                return ResourceManager.GetString("Not_Exixting_Delivery_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vehículo no cumple con las condiciones para generar el acta de entrega.
        /// </summary>
        public static string Not_Meet_Conditions_To_Generate_Delivery_Certificate {
            get {
                return ResourceManager.GetString("Not_Meet_Conditions_To_Generate_Delivery_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de la orden {0:dd/MM/yyyy} es mayor a la fecha que está intentando ingresar {1:dd/MM/yyyy}.
        /// </summary>
        public static string Order_Date_Is_Greater {
            get {
                return ResourceManager.GetString("Order_Date_Is_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de accesorios no está en proceso.
        /// </summary>
        public static string OrderAccessories_Not_In_Process {
            get {
                return ResourceManager.GetString("OrderAccessories_Not_In_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro {0} no fue encontrado.
        /// </summary>
        public static string Parameter_Not_Exist {
            get {
                return ResourceManager.GetString("Parameter_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vehículo no existe en la base de datos.
        /// </summary>
        public static string Vehicle_Not_Exist {
            get {
                return ResourceManager.GetString("Vehicle_Not_Exist", resourceCulture);
            }
        }
    }
}
