version: 2.1 

orbs:
  windows: circleci/windows@2.4.0

jobs: 
  build:
    executor: 
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ./Renting.MasterServices.sln
      - run:
          name: "Run application test"
          command: dotnet.exe build ./Renting.MasterServices.sln --configuration Release  