version: 2.1 
orbs:
  windows: circleci/windows@2.4.0

jobs: 
  tets:
    description: Setup and run application tests
    executor: 
      name: windows/default
    steps:
      - checkout
      - restore_cache:
        keys:
          - dotnet-packages-v1-{{ checksum "Renting.MasterServices.sln" }}
      - run:
        name: "Install project dependencies"
        command: dotnet.exe restore ./Renting.MasterServices.sln
      - save_cache:
        paths: 
          - C:\Users\circleci\.nuget\packages
        key: dotnet-packages-v1-{{ checksum "Renting.MasterServices.sln" }}
      - run:
        name: 'Run application test'
        command: dotnet.exe test ./Renting.MasterServices.core.Test -v --results-directory:test_coverage --collect:"Code Coverage"
      - run:
        name: "Print Working Directory"
        command: pwd
      - store_artifacts:
        path: C:\Users\circleci\project\test_coverage
  
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build ./Renting.MasterServices.sln --configuration Release          

workflow:
  test_and_build:
    jobs: 
      - test
      - build:
        required:
          -test
  
