version: 2.1 

orbs:
  windows: circleci/windows@2.4.0

jobs: 
  test:
    executor: 
      name: windows/default
    working_directory: /Renting.MasterServices
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ./Renting.MasterServices.sln
      - run:
          name: "Run application test"
          command: dotnet.exe test ./Renting.MasterServices.core.test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: /tmp/test_coverage
  build:
    description: "Build application with Release configuration"
    executor:
      name: windows/default
    working_directory: /Renting.MasterServices
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build ./Renting.MasterServices.sln --configuration Release
  publish:
    description: "Publish application with Release configuration"
    executor:
      name: windows/default
    working_directory: /Renting.MasterServices
    steps:
        - checkout
        - run:
            name: "Publish artifact"
            command: dotnet.exe publish ./Renting.MasterServices.Api/Renting.MasterServices.Api.csproj --configuration Release --output publish_build --self-contained false 
        - store_artifacts:
            path: /tmp/publish_build   

workflows:
  test_and_build_and_publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build      