version: 2.1 

orbs:
  windows: circleci/windows@2.4.0

jobs: 
  test:
    executor: 
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ./Renting.MasterServices.sln
      - run:
          name: "Run application test"
          command: dotnet.exe test ./Renting.MasterServices.sln -v n --results-directory:test_coverage --collect:"Code Coverage"
  build:
    description: "Build application with Release configuration"
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build ./Renting.MasterServices.sln --configuration Release  

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test